const mockBooks = [
  {
    id: "b1",
    title: "The Cocoa Ledger",
    author: "L. Caramel",
    genre: "Fiction",
    price: 199000,
    oldPrice: 249000,
    rating: 4.6,
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=60",
    tags: ["bestseller", "sale"],
    description:
      "A warm tale about trade, memory and the scent of cocoa — ideal for slow afternoons.",
    similar: ["b2", "b3"],
  },
  {
    id: "b2",
    title: "Maple & Margins",
    author: "A. Bentwood",
    genre: "Non-Fiction",
    price: 149000,
    rating: 4.2,
    cover: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=800&q=60",
    tags: ["staff-pick"],
    description: "Notes on making small businesses human again.",
    similar: ["b1"],
  },
  {
    id: "b3",
    title: "Quiet Brown Streets",
    author: "M. Sienna",
    genre: "Fiction",
    price: 129000,
    rating: 4.1,
    cover: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=800&q=60",
    tags: [],
    description: "A meditative novel set in a small town coffee shop.",
    similar: ["b1"],
  },
  {
    id: "b4",
    title: "Designing with Chocolate",
    author: "N. Cocoa",
    genre: "Design",
    price: 299000,
    oldPrice: 349000,
    rating: 4.9,
    cover: "https://images.unsplash.com/photo-1544937954-9f0b2f7d1f8a?auto=format&fit=crop&w=800&q=60",
    tags: ["sale", "premium"],
    description: "A lush visual guide for designers who love tactile color palettes.",
    similar: ["b2", "b3"],
  },
  // ...add more mock items as needed
];